apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
  namespace: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql-server
  template:
    metadata:
      labels:
        app: pgsql-server
    spec:
      containers:
      - name: pgsql-server
        image: postgres
        ports:
        - containerPort:  5432
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: sonar
        - name: POSTGRES_DB
          value: sonar
        - name: POSTGRES_PASSWORD
          value: "rAn0s31528"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: sonar
  name: postgres-svc
  labels:
    app: pgsql-server
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: pgsql-server